---
dependencies: []

galaxy_info:
  role_name: adfs_kerberos_auth
  author: Andrew Gomez
  description: Configure Kerberos Auth
  company: SpecterOps
  license: GPLv3
  min_ansible_version: "2.10"
  version: "1.1.1"
  platforms:
    - name: Windows
      versions:
        - "2012R2"
        - "2016"
        - "2019"
        - "2022"

  galaxy_tags:
    - windows
    - security
    - adfs
    - activedirectory
    - server
    - ludus
